# Use Node.js as the base image
FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps

RUN apk add --no-cache libc6-compat

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

# Accept build arguments
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG GOOGLE_SERVICE_ACCOUNT_KEY_JSON
ARG NODE_ENV
ARG NEXT_PUBLIC_GEMINI_API_KEY

# Set environment variables
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ENV GOOGLE_SERVICE_ACCOUNT_KEY_JSON=$GOOGLE_SERVICE_ACCOUNT_KEY_JSON
ENV NODE_ENV=$NODE_ENV
ENV NEXT_PUBLIC_GEMINI_API_KEY=$NEXT_PUBLIC_GEMINI_API_KEY

RUN --mount=type=secret,id=NEXT_PUBLIC_API_URL \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_API_KEY \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_PROJECT_ID \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_APP_ID \
    --mount=type=secret,id=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
    --mount=type=secret,id=GOOGLE_SERVICE_ACCOUNT_KEY_JSON \
    --mount=type=secret,id=NEXT_PUBLIC_GEMINI_API_KEY \
    export NEXT_PUBLIC_API_URL=$(cat /run/secrets/NEXT_PUBLIC_API_URL) && \
    export NEXT_PUBLIC_FIREBASE_API_KEY=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_API_KEY) && \
    export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN) && \
    export NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID) && \
    export NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET) && \
    export NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID) && \
    export NEXT_PUBLIC_FIREBASE_APP_ID=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_APP_ID) && \
    export NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$(cat /run/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID) && \
    export GOOGLE_SERVICE_ACCOUNT_KEY_JSON=$(cat /run/secrets/GOOGLE_SERVICE_ACCOUNT_KEY_JSON) && \
    export NEXT_PUBLIC_GEMINI_API_KEY=$(cat /run/secrets/NEXT_PUBLIC_GEMINI_API_KEY) && \
    pnpm run build

EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]